export const GET_INVOICE_LIST_REQUEST = "GET_INVOICE_LIST_REQUEST";
export const GET_INVOICE_LIST_SUCCESS = "GET_INVOICE_LIST_SUCCESS";
export const GET_INVOICE_LIST_FAILURE = "GET_INVOICE_LIST_FAILURE";

export const HANDLE_ADD_INVOICE_MODAL = "HANDLE_ADD_INVOICE_MODAL";

export const HANDLE_EDIT_INVOICE_MODAL = "HANDLE_EDIT_INVOICE_MODAL";
